import frappe
from frappe import _
from frappe.model.document import Document


class BOMUpdateRequest(Document):
	def before_insert(self):
		self._create_kit_content_mapping()

	def after_insert(self):
		# Back-link the KCM to this BUR now that self.name is assigned.
		if self.kit_content_mapping:
			frappe.db.set_value(
				"Kit Content Mapping",
				self.kit_content_mapping,
				"bom_update_request",
				self.name,
			)

	def _create_kit_content_mapping(self):
		if not self.current_bom or not self.fg_item:
			frappe.throw(_("FG Item and Current BOM are required."))

		bom_doc = frappe.get_doc("BOM", self.current_bom)

		kcm = frappe.new_doc("Kit Content Mapping")
		kcm.fg_item = self.fg_item
		kcm.source_bom = self.current_bom
		# bom_update_request will be back-linked in after_insert once we
		# have our own name. Set ignore_mandatory since kit_content_framework
		# is legitimately blank at creation time in the BUR flow.
		kcm.flags.ignore_mandatory = True

		for bom_item in bom_doc.items:
			# Preserve the node link if the BOM was previously generated by
			# this app (node field is a Link to Kit Content Node). Validate
			# it still exists before linking — old BOMs stored breadcrumb
			# strings which won't resolve as Kit Content Node names.
			node_name = bom_item.get("node") or None
			if node_name and not frappe.db.exists("Kit Content Node", node_name):
				node_name = None

			kcm.append(
				"mapping_items",
				{
					"node_name": node_name,
					"indent_level": 1,
					"framework_node_type": "Purchase",
					"treatment": "",
					"item_code": bom_item.item_code,
					"qty": bom_item.qty,
					"uom": bom_item.uom
					or frappe.db.get_value("Item", bom_item.item_code, "stock_uom"),
				},
			)

		kcm.insert(ignore_permissions=True)
		self.kit_content_mapping = kcm.name

	# ------------------------------------------------------------------ #
	# Lifecycle transitions
	# ------------------------------------------------------------------ #

	@frappe.whitelist()
	def submit_for_review(self):
		if self.status != "Draft":
			frappe.throw(_("Only Draft requests can be submitted for review."))
		if not self.kit_content_mapping:
			frappe.throw(_("No Kit Content Mapping is linked — save this request first."))
		self.status = "Submitted"
		self.save()

	@frappe.whitelist()
	def approve(self):
		"""Approve and immediately trigger BOM generation from the linked
		Kit Content Mapping. Returns the list of BOM names created."""
		if self.status != "Submitted":
			frappe.throw(_("Only Submitted requests can be approved."))
		self.status = "Approved"
		self.save()
		if self.kit_content_mapping:
			kcm = frappe.get_doc("Kit Content Mapping", self.kit_content_mapping)
			return kcm.generate_pending_boms()
		return []

	@frappe.whitelist()
	def reject(self, reason=""):
		if self.status != "Submitted":
			frappe.throw(_("Only Submitted requests can be rejected."))
		self.status = "Rejected"
		self.rejection_reason = reason or ""
		self.save()
